### ISSUE TITLE
Lecture 1 typos

### ISSUE THREAD

**Issue by rjrosati** [Majoburo/PHY-387M#1]
Just some suggestions:

- The last figure doesn't actually have the worldline exiting the light cone. Maybe this should actually have the line puncturing the cone, for dramatic effect

- none of the figures are numbered

- the "quick note" above (2.4) should probably be a side note `\sn{}`

- (1.10) should be two lines

**Comment by Majoburo** [comment]
I agree. Anyone up for editing this?
